name: Rust

on:
  pull_request:
    branches: [ "master" ]
    types:
      - closed
  

env:
  CARGO_TERM_COLOR: always

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cargo login
      run: cargo login ${{ secrets.CRATES_IO }}
    - name: publish
      run: cargo publish
